### ISSUE TITLE
Unlisted App Install results in a Shopify 404

### ISSUE THREAD

**Issue by kneeki** [osiset/laravel-shopify#395]
## Expected Behavior
The user clicks 'install', is redirected to my server, and taken back to Shopify to agree and finally install the app.

## Current Behavior
After clicking 'install' the redirect occurs but once I get back to Shopify I'm given a 404.

![image](https://user-images.githubusercontent.com/1012169/75130566-ec193180-5683-11ea-81e4-7bad4da13ed7.png)

## Failure Information
No information to give?

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Click 'install' to development store

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v10.3
* Laravel Version: v6.2
* PHP Version: v7.2
* ngrok

### Failure Logs
Apache2 Error log:
```
[Sun Feb 23 21:32:16.750593 2020] [socache_shmcb:debug] [pid 21178] mod_socache_shmcb.c(854): AH00848: finished insert, subcache: idx_pos/idx_used=0/1, data_pos/data_used=0/180
[Sun Feb 23 21:32:16.750602 2020] [socache_shmcb:debug] [pid 21178] mod_socache_shmcb.c(516): AH00834: leaving socache_shmcb_store successfully
[Sun Feb 23 21:32:16.750623 2020] [ssl:debug] [pid 21178] ssl_engine_kernel.c(2067): [client 127.0.0.1:52081] AH02041: Protocol: TLSv1.2, Cipher: ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)      
[Sun Feb 23 21:32:16.750701 2020] [ssl:debug] [pid 21178] ssl_engine_kernel.c(377): [client 127.0.0.1:52081] AH02034: Initial (No.1) HTTPS request received for child 2 (server www.deeplinker.local:443), referer: https://partners.shopify.com/
[Sun Feb 23 21:32:16.751074 2020] [authz_core:debug] [pid 21178] mod_authz_core.c(809): [client 127.0.0.1:52081] AH01626: authorization result of Require all granted: granted, referer: https://partners.shopify.com/
[Sun Feb 23 21:32:16.751098 2020] [authz_core:debug] [pid 21178] mod_authz_core.c(809): [client 127.0.0.1:52081] AH01626: authorization result of <RequireAny>: granted, referer: https://partners.shopify.com/
[Sun Feb 23 21:32:16.752342 2020] [authz_core:debug] [pid 21178] mod_authz_core.c(809): [client 127.0.0.1:52081] AH01626: authorization result of Require all granted: granted, referer: https://partners.shopify.com/
[Sun Feb 23 21:32:16.752365 2020] [authz_core:debug] [pid 21178] mod_authz_core.c(809): [client 127.0.0.1:52081] AH01626: authorization result of <RequireAny>: granted, referer: https://partners.shopify.com/
[Sun Feb 23 21:32:16.833105 2020] [deflate:debug] [pid 21178] mod_deflate.c(854): [client 127.0.0.1:52081] AH01384: Zlib: Compressed 1523 to 612 : URL /index.php, referer: https://partners.shopify.com/
[Sun Feb 23 21:32:21.833903 2020] [ssl:debug] [pid 21178] ssl_engine_io.c(1106): [client 127.0.0.1:52081] AH02001: Connection closed to child 2 with standard shutdown (server www.deeplinker.local:443)
```
Here's an error in the console:
```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://xxx.myshopify.com') does not match the recipient window's origin ('https://9332e1dc.ngrok.io').
```

This URL directly results in a 404 from Shopify:
```
https://xxx.myshopify.com/admin/apps/xxx/?hmac=xxx&shop=xxx.myshopify.com&timestamp=1582522336
```

Please include any relevant log snippets or files here.

**Comment by RandomWeasel** [comment]
I'm having the same issue with a similar setup, also using ngrok to access my local development environment, and trying to install an unlisted app.

When installing the app, I go via the partners dashboard, and select to install the app on a development store.  I select the relevant store and am redirected to the 'install' screen - in the console I see the two logs shown below - the first is the redirect to my authenticate route (as listed in the redirect routes in app settings), and then the redirect back to the shopify store for authentication

![image](https://user-images.githubusercontent.com/16453825/75764190-6d805c00-5d35-11ea-9815-8b98fa72b551.png)

At this point (before clicking 'Install'), I have a record created in the 'shops' table with the shopify_domain but no shopify_token 

I then click 'Install' and see another log

![image](https://user-images.githubusercontent.com/16453825/75764617-04e5af00-5d36-11ea-9e1b-be417e8665d1.png)

I then get slightly weird results, as sometimes I get the behaviour described by kneeki (a shopify 404) page, and other times I am redirected to my ngrok address


**local version**
I see another log message
![image](https://user-images.githubusercontent.com/16453825/75764774-48401d80-5d36-11ea-8a63-10ab7cde1a23.png)
The browser url is now my localhost tunnel address, and a 500 error is thrown - presumably because the url is missing the expected shop domain.
I have a shopify_token saved on the database record
If I view the 'apps' page for my store, my newly installed app is shown.
If I click the app name, I am sent to the store url https://custom-peaks-uk.myshopify.com/admin/apps/demo-app-115 and can view the app correctly
So in this case, it seems to be an issue with redirecting to the correct shopify url rather than just the 'app url' - the install appears to have worked correctly.
If billing is enabled, and I click 'accept charge', I am again redirected to my localhost address

**404 version**
This is a weird one because it doesn't happen every time, and I haven't been able to work out what triggers this to happen (including now, whilst trying to write up some info!).
I thought it may have been happening when I had deleted the app via the store's App page, and not removed the database record, but this doesn't seem to be the case.
The url I am directed to is something along the lines of https://custom-peaks-uk.myshopify.com/admin/apps/1234567 (I can't remember the actual string of numbers), but it is a different url to which I would usually view my app at.  I see a shopify 404 page as described in the original post.  I've also noticed that, more often than not, if I return to the stores 'Apps' page, the new app is not listed - it appears not to have been correctly installed, and if I remember correctly, the shopify_token has not been added to the database.  I generally cannot reach the app by pasting in the usual url, which again makes me think something went wrong during install.

Apologies I wasn't able to give as much detail on the 404 behaviour, but I hope some of that is helpful... let me know if I can help with any more info, and if I manage to get the 404 to happen again I will update with any further detail!

**Comment by Kyon147** [comment]
@RandomWeasel have you tried clearing your browser cache? There was an issue with logging in on #400 which was solved this way.

**Comment by kneeki** [comment]
@Kyon147 I did, same results for me. Even tried a different browser.

**Comment by RandomWeasel** [comment]
@Kyon147 I've just tried again after clearing cache on the shopify domain and my local domain, and also in an incognito window, but I'm still getting the same problem.  It seems like after the 'authenticate' step, the browser is being redirected to the app url rather than the shopify url.  

I've got the 'authenticate' url in my whitelisted redirection urls as per the setup instructions, but nothing else - should there perhaps be another url here that's missing?

**Comment by kneeki** [comment]
Is there a solution to this somewhere @osiset?

**Comment by Kyon147** [comment]
Issues around pre v11 are probably not going to given a huge amount of time. As the maintainer osiset can't manage to look multiple codebases. If you have just started an app - move to v11 as it would be much quicker to fix.

If you have the issue on a built app - could be worth looking at the migration. 

I have an app on pre v11 - so will be fixing the odd issue on my own app until I am ready to move over. So if I find the solution I will update the relevant issues.
